title: Juan NÃºÃ±ez # your name (or website title) here
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist at Platzi Master Program | Biomedical engineer. 
  <br><br>
  ðŸ§ Iâ€™m always learning about Data Science, Machine Learning and Artificial Intelligence.
  ðŸ¤”I'm interested Image processing and Data analysis. 
  ðŸ“« How to reach me: juanpa.nb@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/juanpanu/">View My LinkedIn Profile</a> 
 
  
theme: jekyll-theme-minimal
